steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/learnnova', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/learnnova']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'learnnova', '--image', 'gcr.io/$PROJECT_ID/learnnova', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/$PROJECT_ID/learnnova
